apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: argocd
  labels:
    name: busybox
spec:
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "18000"
    name: busybox
